In [27]:
import numpy as np

A = np.array([[3, -0.1, -0.2, 7.85], [0.1, 7, -0.3, -19.3], [0.3, -0.2, 10, 71.4]])

print "Sistema Ecuaciones Propuesto:"
print "Matriz A:"
print A, "\n"

n=3

# Eliminación de Gauss Simple hacia adelante
for k in range(0, n-1):
    for i in range(k+1, n):
        factor = A[i,k] / (A[k,k] * 1.0)
        for j in range(k,n):
            A[i,j] = A[i,j] - factor * A[k,j]
        A[i,n] = A[i,n] - factor * A[k,n]
print "Resultados:"
print ""
print "Matriz A (Eliminacion hacia adelante):"
print A
print "Matriz A (Sustitución hacia atrás)"
B=A[n-1,n-1]
for k in range(0, n+1):
    A[n-1,k]=(A[n-1,k]/B)
    A[n-2,k]=(A[n-2,k]*2)
print A


Sistema Ecuaciones Propuesto:
Matriz A:
[[  3.    -0.1   -0.2    7.85]
 [  0.1    7.    -0.3  -19.3 ]
 [  0.3   -0.2   10.    71.4 ]] 

Resultados:

Matriz A (Eliminacion hacia adelante):
[[  3.          -0.1         -0.2          7.85      ]
 [  0.           7.00333333  -0.29333333 -19.56166667]
 [  0.           0.          10.01204188  70.08429319]]
Matriz A (Sustitución hacia atrás)
[[  3.          -0.1         -0.2          7.85      ]
 [  0.          14.00666667  -0.58666667 -39.12333333]
 [  0.           0.           1.           7.        ]]
